[package]
name = "value-encoding"
version = "0.1.0"
edition = "2021"
description = "Value encoding format."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
memcomparable = { path = "../memcomparable" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
rand = "0.8"
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
