[package]
name = "risingwave_cmd_all"
version = "0.1.7"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
log = { version = "0.4", features = ["release_max_level_info"] }
risedev = { path = "../risedevtool" }
risingwave_compactor = { path = "../storage/compactor" }
risingwave_compute = { path = "../compute" }
risingwave_ctl = { path = "../ctl" }
risingwave_frontend = { path = "../frontend" }
risingwave_logging = { path = "../utils/logging" }
risingwave_meta = { path = "../meta" }
tikv-jemallocator = "0.4"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tracing = { version = "0.1", features = ["release_max_level_info"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[[bin]]
name = "risingwave"
path = "src/bin/risingwave.rs"
