[package]
name = "risingwave_cmd_all"
version = "0.1.10"
edition = "2021"

[features]
static-link = ["workspace-static-link"]

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
log = { version = "0.4", features = ["release_max_level_info"] }
madsim = "=0.2.0-alpha.3"
risedev = { path = "../risedevtool" }
risingwave_compactor = { path = "../storage/compactor" }
risingwave_compute = { path = "../compute" }
risingwave_ctl = { path = "../ctl" }
risingwave_frontend = { path = "../frontend" }
risingwave_meta = { path = "../meta" }
risingwave_rt = { path = "../utils/runtime" }
tikv-jemallocator = "0.5"
tokio = { version = "=0.2.0-alpha.3", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tracing = { version = "0.1", features = ["release_max_level_info"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
workspace-static-link = { path = "../utils/static-link", optional = true, features = ["enabled"] }

[[bin]]
name = "risingwave"
path = "src/bin/risingwave.rs"
