[package]
name = "piestream_cmd_all"
version = "0.1.13"
edition = "2021"

[features]
static-link = ["workspace-config/enable-static-link"]
static-log-level = ["workspace-config/enable-static-log-level"]

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
global_stats_alloc = { path = "../utils/global_stats_alloc" }
log = { version = "0.4" }
risedev = { path = "../risedevtool" }
piestream_common = { path = "../common" }
piestream_compactor = { path = "../storage/compactor" }
piestream_compute = { path = "../compute" }
piestream_ctl = { path = "../ctl" }
piestream_frontend = { path = "../frontend" }
piestream_meta = { path = "../meta" }
piestream_rt = { path = "../utils/runtime" }
stats_alloc = { version = "0.1", features = ["nightly"] }
sync-point = { path = "../utils/sync-point" }
tikv-jemallocator = { version = "0.5", features = ["profiling", "stats"] }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tracing = { version = "0.1" }
workspace-config = { path = "../utils/workspace-config", optional = true }
workspace-hack = { version = "0.1.13", path = "../workspace-hack" }

[[bin]]
name = "piestream"
path = "src/bin/piestream.rs"
