[package]
name = "piestream_meta"
version = "0.1.10"
edition = "2021"

[dependencies]
anyhow = "1"
assert_matches = "1"
async-recursion = "1"
async-stream = "0.3"
async-trait = "0.1"
axum = "0.5"
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "3", features = ["derive"] }
crc32fast = "1"
derivative = "2"
either = "1"
etcd-client = "0.9"
fail = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hex = "0.4"
hyper = "0.14"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
madsim = "=0.2.0-alpha.3"
memcomparable = { path = "../utils/memcomparable" }
num-integer = "0.1"
num-traits = "0.2"
parking_lot = { version = "0.12", features = ["arc_lock"] }
paste = "1"
prometheus = "0.13"
prost = "0.10"
rand = "0.8"
piestream_common = { path = "../common" }
piestream_connector = { path = "../connector" }
piestream_hummock_sdk = { path = "../storage/hummock_sdk" }
piestream_pb = { path = "../prost" }
piestream_rpc_client = { path = "../rpc_client" }
scopeguard = "1"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
smallvec = "1"
thiserror = "1"
tokio = { version = "=0.2.0-alpha.3", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "=0.2.0-alpha.3", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tower-http = { version = "0.3", features = ["add-extension", "cors", "fs"] }
tracing = { version = "0.1" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
rand = "0.8"
piestream_test_runner = { path = "../test_runner" }
static_assertions = "1"
tempfile = "3"

[target.'cfg(not(madsim))'.dev-dependencies]
piestream_frontend = { path = "../frontend" }

[features]
test = []
failpoints = ["fail/failpoints"]
