header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: PieDb Data

  paths:
    - "src/**/*.rs"
    - "dashboard/**/*.js"
    - "dashboard/**/*.ts"
    - "src/**/*.html"

  paths-ignore:
    - "**/gen/**"
    - "**/*.d.ts"

  comment: on-failure