[workspace]
members = [
  "src/batch",
  "src/bench",
  "src/cmd",
  "src/cmd_all",
  "src/common",
  "src/compute",
  "src/connector",
  "src/ctl",
  "src/expr",
  "src/frontend",
  "src/frontend/test_runner",
  "src/meta",
  "src/prost",
  "src/prost/helpers",
  "src/risedevtool",
  "src/rpc_client",
  "src/source",
  "src/sqlparser",
  "src/sqlparser/test_runner",
  "src/storage",
  "src/storage/compactor",
  "src/storage/hummock_sdk",
  "src/stream",
  "src/tests/regress",
  "src/utils/logging",
  "src/utils/memcomparable",
  "src/utils/pgwire",
  "src/utils/value-encoding",
  "src/workspace-hack",
]

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false

[profile.release]
debug = true
