disallowed-methods = [
    { path = "std::iter::Iterator::zip", reason = "Please use Itertools::zip_eq instead." },
    { path = "futures::stream::select_all", reason = "Please use `piestream_common::util::select_all` instead." },
]
doc-valid-idents = [
    "piestream",
    "MinIO",
    "ProtoBuf",
    "BloomFilter",
    "gRPC",
    "PostgreSQL",
    "MySQL",
    "TopN",
    "VNode"
]
avoid-breaking-exported-api = false
upper-case-acronyms-aggressive = true
