# codecov config
# Reference: https://docs.codecov.com/docs/codecovyml-reference
# Tips. You may run following command to validate before committing any changes
#   curl --data-binary @codecov.yml https://codecov.io/validate
coverage:
  status:
    patch: off # disable patch status
    project: 
      default: false  # disable the default status that measures entire project
      rust:
        only_pulls: true # no status will be posted for commits not on a pull request
        paths:
          - "src/"
        target: auto # compared with the coverage from the base commit
        threshold: 0.1% # allow the coverage to drop by 0.1% and posting a success status
ignore:
  - "src/risedevtooltool"
  - "src/bench/s3_bench"
  # Remove this after #4754
  - "src/storage/src/hummock/store"
