[[case]]
type = "Put"
[case.args]
name = "s3 - put - 1MiB"
obj = "1MiB"
size = "1MiB"

[[case]]
type = "Put"
[case.args]
name = "s3 - put - 8MiB"
obj = "8MiB"
size = "8MiB"

[[case]]
type = "Put"
[case.args]
name = "s3 - put - 64MiB"
obj = "64MiB"
size = "64MiB"

[[case]]
type = "Put"
[case.args]
name = "s3 - put - 128MiB"
obj = "128MiB"
size = "128MiB"

[[case]]
type = "Put"
[case.args]
name = "s3 - put - 256MiB"
obj = "256MiB"
size = "256MiB"

[[case]]
type = "MultiPartUpload"
[case.args]
name = "s3 - multi part upload - 1MiB-p8MiB"
obj = "1MiB-p8MiB"
size = "1MiB"
part = "8MiB"

[[case]]
type = "MultiPartUpload"
[case.args]
name = "s3 - multi part upload - 8MiB-p8MiB"
obj = "8MiB-p8MiB"
size = "8MiB"
part = "8MiB"

[[case]]
type = "MultiPartUpload"
[case.args]
name = "s3 - multi part upload - 64MiB-p8MiB"
obj = "64MiB-p8MiB"
size = "64MiB"
part = "8MiB"

[[case]]
type = "MultiPartUpload"
[case.args]
name = "s3 - multi part upload - 128MiB-p8MiB"
obj = "128MiB-p8MiB"
size = "128MiB"
part = "8MiB"

[[case]]
type = "MultiPartUpload"
[case.args]
name = "s3 - multi part upload - 256MiB-p8MiB"
obj = "256MiB-p8MiB"
size = "256MiB"
part = "8MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get - 1MiB"
obj = "1MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get - 8MiB"
obj = "8MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get - 64MiB"
obj = "64MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get - 128MiB"
obj = "128MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get (parted) - 1MiB-p8MiB"
obj = "1MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get (parted) - 8MiB-p8MiB"
obj = "8MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get (parted) - 64MiB-p8MiB"
obj = "64MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get (parted) - 128MiB-p8MiB"
obj = "128MiB"

[[case]]
type = "Get"
[case.args]
name = "s3 - get (parted) - 256MiB-p8MiB"
obj = "256MiB"

[[case]]
type = "MultiPartGet"
[case.args]
name = "s3 - multi part get (all) - 1MiB-p8MiB"
obj = "1MiB-p8MiB"
part = [1]

[[case]]
type = "MultiPartGet"
[case.args]
name = "s3 - multi part get (all) - 8MiB-p8MiB"
obj = "8MiB-p8MiB"
part = [1]

[[case]]
type = "MultiPartGet"
[case.args]
name = "s3 - multi part get (all) - 64MiB-p8MiB"
obj = "64MiB-p8MiB"
part = [1, 2, 3, 4, 5, 6, 7, 8]

[[case]]
type = "MultiPartGet"
[case.args]
name = "s3 - multi part get (all) - 128MiB-p8MiB"
obj = "128MiB-p8MiB"
part = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

[[case]]
type = "MultiPartGet"
[case.args]
name = "s3 - multi part get (all) - 256MiB-p8MiB"
obj = "256MiB-p8MiB"
part = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32]

[[case]]
type = "MultiPartGet"
[case.args]
name = "s3 - multi part get (3 4) - 64MiB-p8MiB"
obj = "64MiB-p8MiB"
part = [3, 4]

[[case]]
type = "MultiPartGet"
[case.args]
name = "s3 - multi part get (3 4) - 128MiB-p8MiB"
obj = "128MiB-p8MiB"
part = [3, 4]

[[case]]
type = "ByteRangeGet"
[case.args]
name = "s3 - byte range get (fit 2 parts) - 64MiB-p8MiB"
obj = "64MiB-p8MiB"
start = 16777216 # 16MiB
end = 33554431 # 32MiB - 1

[[case]]
type = "ByteRangeGet"
[case.args]
name = "s3 - byte range get (fit 2 parts) - 128MiB-p8MiB"
obj = "128MiB-p8MiB"
start = 16777216 # 16MiB
end = 33554431 # 32MiB - 1

[[case]]
type = "ByteRangeGet"
[case.args]
name = "s3 - byte range get (unfit 2 parts) - 64MiB-p8MiB"
obj = "64MiB-p8MiB"
start = 19922944 # 19MiB
end = 36700159 # 35MiB - 1

[[case]]
type = "ByteRangeGet"
[case.args]
name = "s3 - byte range get (unfit 2 parts) - 128MiB-p8MiB"
obj = "128MiB-p8MiB"
start = 19922944 # 19MiB
end = 36700159 # 35MiB - 1