[package]
edition = "2021"
name = "risingwave_connector"
version = "0.1.7"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
aws-config = { version = "0.11", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-sdk-kinesis = { version = "0.11", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-sdk-s3 = { version = "0.11", default-features = false, features = ["rt-tokio","native-tls"] }
aws-sdk-sqs = { version = "0.11", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-smithy-http = "0.41"
aws-smithy-types = "0.41"
aws-types = { version = "0.11", features = ["hardcoded-credentials"] }
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = "0.4"
crc32fast = "1"
either = "1"
farmhash = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
futures-concurrency = "2.0.3"
globset = "0.4.8"
http = "0.2"
http-serde = "1.1.0"
hyper = "0.14"
itertools = "0.10"
log = "0.4"
maplit = "1.0.2"
memcomparable = { path = "../utils/memcomparable" }
num-traits = "0.2"
paste = "1"
prost = "0.10"
protobuf = "2"
pulsar = { git = "https://github.com/singularity-data/pulsar-rs.git", rev = "8d4789eea780d520136e1cc2535a1fec9385c53d", default-features = false, features = ["tokio-runtime"] }
rand = "0.8"
rdkafka = { version = "0.28", features = ["cmake-build"] }
risingwave_common = { path = "../common" }
risingwave_pb = { path = "../prost" }
risingwave_storage = { path = "../storage" }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
smallvec = "1"
static_assertions = "1"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal", "fs"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec", "io"] }
tonic = { version = "0.2.0-alpha.1", package = "madsim-tonic" }
twox-hash = "1"
url = "2"
urlencoding = "2"

workspace-hack = { version = "0.1", path = "../workspace-hack" }
[dev-dependencies]
rand = "0.8"
tempfile = "3"
wiremock = "0.5"
