[package]
edition = "2021"
name = "risingwave_pb"
version = "0.1.10"

[dependencies]
bytes = "1"
pbjson = "0.3"
prost = "0.10"
prost-helpers = { path = "helpers" }
prost-types = "0.10"
serde = { version = "1", features = ["derive"] }
tonic = { version = "=0.2.0-alpha.3", package = "madsim-tonic" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[build-dependencies]
pbjson-build = "0.3"
tonic-build = { version = "=0.2.0-alpha.1", package = "madsim-tonic-build" }
