{
 "title": "piestream_dashboard",
 "description": "piestream Dashboard",
 "tags": [ "piestream" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes) by (job,instance)",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) by (job,instance)",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SST Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(storage_level_sst_num) by (instance, level_index)",
     "legendFormat": "L{{level_index}}"
    }
   ]
  },
  {
   "title": "KBs level sst",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(storage_level_total_file_size) by (instance, level_index)",
     "legendFormat": "L{{level_index}}"
    }
   ]
  },
  {
   "title": "Compaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "storage_level_compact_frequency",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Compaction Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_compact_task_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "compact-task p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_compact_task_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "compact-task p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le)(rate(state_store_compact_task_duration_sum[1m])) / sum by(le) (rate(state_store_compact_task_duration_count[1m]))",
     "legendFormat": "compact-task avg"
    },
    {
     "expr": "sum by(le)(rate(state_store_compact_sst_duration_sum[1m])) / sum by(le) (rate(state_store_compact_sst_duration_count[1m]))",
     "legendFormat": "compact-key-range avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_compact_sst_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "compact-key-range p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_get_table_id_total_time_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "get-table-id p90 {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_remote_read_time_per_task_bucket[1m])) by (le, job, instance))",
     "legendFormat": "remote-io p90 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Compaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(storage_level_compact_read_next[1m])) by(job,instance) + sum(rate(storage_level_compact_read_curr[1m])) by(job,instance)",
     "legendFormat": "read - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(storage_level_compact_write[1m])) by(job,instance)",
     "legendFormat": "write - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_write_build_l0_bytes[1m]))by (job,instance)",
     "legendFormat": "flush - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Compacting SST Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "storage_level_compact_cnt", "legendFormat": "L{{level_index}}" }
   ]
  },
  {
   "title": "KBs Read from Next Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(storage_level_compact_read_next[1m])) by (le, level_index)",
     "legendFormat": "L{{level_index}} read"
    }
   ]
  },
  {
   "title": "KBs Read from Current Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(storage_level_compact_read_curr[1m])) by (le, level_index)",
     "legendFormat": "L{{level_index}} read"
    }
   ]
  },
  {
   "title": "Count of SSTs Read from Current Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(storage_level_compact_read_sstn_curr[1m])) by (le, level_index)",
     "legendFormat": "L{{level_index}} read"
    }
   ]
  },
  {
   "title": "KBs Written to Next Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(storage_level_compact_write[1m])) by (le, level_index)",
     "legendFormat": "L{{level_index}} write"
    }
   ]
  },
  {
   "title": "Count of SSTs Written to Next Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(storage_level_compact_write_sstn[1m])) by (le, level_index)",
     "legendFormat": "L{{level_index}} write"
    }
   ]
  },
  {
   "title": "Count of SSTs Read from Next Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(storage_level_compact_read_sstn_next[1m])) by (le, level_index)",
     "legendFormat": "L{{level_index}} read"
    }
   ]
  },
  {
   "title": "Hummock Version Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "version_size", "legendFormat": "version size" }
   ]
  },
  { "title": "Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(object_store_read_bytes[1m]))by(job,instance)",
     "legendFormat": "read - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(object_store_write_bytes[1m]))by(job,instance)",
     "legendFormat": "write - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Operation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(object_store_operation_latency_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}} p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(object_store_operation_latency_bucket[1m])) by (le, type, job, instance))",
     "legendFormat": "{{type}} p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_latency_bucket[1m])) by (le, type, job, instance))",
     "legendFormat": "{{type}} p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, type)(rate(object_store_operation_latency_sum[1m])) / sum by(le, type) (rate(object_store_operation_latency_count[1m]))",
     "legendFormat": "{{type}} avg"
    }
   ]
  },
  {
   "title": "Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(object_store_operation_latency_count[1m])) by (le, type, job, instance)",
     "legendFormat": "{{type}} - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Op Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_bytes_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}  p90"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(object_store_operation_bytes_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}} p80"
    }
   ]
  },
  {
   "title": "Estimated S3 Cost (Realtime)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "expr": "sum(object_store_operation_latency_count{type=~'read|delete'}) * 0.0004 / 1000",
     "legendFormat": "GET + DELETE Request Cost"
    },
    {
     "expr": "sum(object_store_operation_latency_count{type='upload'}) * 0.005 / 1000",
     "legendFormat": "PUT Request Cost"
    }
   ]
  },
  {
   "title": "Estimated S3 Cost (Monthly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "targets": [
    {
     "expr": "sum(storage_level_total_file_size) by (instance) * 0.023 / 1000 / 1000",
     "legendFormat": "Monthly Storage Cost"
    }
   ]
  },
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Barrier Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    { "expr": "all_barrier_nums", "legendFormat": "all_barrier" },
    { "expr": "in_flight_barrier_nums", "legendFormat": "in_flight_barrier" }
   ]
  },
  {
   "title": "Barrier Send Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_send_duration_seconds_bucket[15s])) by (le))",
     "legendFormat": "barrier_send_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_send_duration_seconds_bucket[15s])) by (le))",
     "legendFormat": "barrier_send_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_send_duration_seconds_bucket[15s])) by (le))",
     "legendFormat": "barrier_send_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_send_duration_seconds_bucket[15s])) by (le))",
     "legendFormat": "barrier_send_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_send_duration_seconds_bucket[15s])) by (le))",
     "legendFormat": "barrier_send_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_send_duration_seconds_sum[15s]) / rate(meta_barrier_send_duration_seconds_count[15s])",
     "legendFormat": "barrier_send_latency_avg"
    }
   ]
  },
  {
   "title": "Barrier Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "barrier_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_duration_seconds_sum[1m]) / rate(meta_barrier_duration_seconds_count[1m])",
     "legendFormat": "barrier_latency_avg"
    }
   ]
  },
  {
   "title": "Source Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "rate(stream_source_output_rows_counts[15s])",
     "legendFormat": "source_id = {{source_id}}"
    },
    {
     "expr": "rate(partition_input_count[5s])",
     "legendFormat": "{{actor_id}}-{{source_id}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Streaming Actors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "rate(stream_executor_row_count[15s]) > 0",
       "legendFormat": "{{actor_id}}->{{executor_id}}"
      }
     ]
    },
    {
     "title": "Actor Sampled Deserialization Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "actor_sampled_deserialize_duration_ns",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Sampled Serialization Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "actor_sampled_serialize_duration_ns",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Backpressure Time Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(stream_actor_output_buffer_blocking_duration[15s])",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Barrier Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_barrier_time[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_processing_time[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_actor_execution_time[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Input Row",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "rate(stream_actor_in_record_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Output Row",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "rate(stream_actor_out_record_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_duration[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_duration[1m]) / rate(stream_actor_fast_poll_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_duration[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_duration[1m]) / rate(stream_actor_slow_poll_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_duration[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_duration[1m]) / rate(stream_actor_poll_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_duration[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_duration[1m]) / rate(stream_actor_idle_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_duration[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_duration[1m]) / rate(stream_actor_scheduled_cnt[1m]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Join Executor Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_join_lookup_miss_count[1m])",
       "legendFormat": "cache miss {{actor_id}} {{side}}"
      },
      {
       "expr": "rate(stream_join_lookup_total_count[1m])",
       "legendFormat": "total lookups {{actor_id}} {{side}}"
      }
     ]
    },
    {
     "title": "Join Executor Barrier Align",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(stream_join_barrier_align_duration_bucket[1m])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "p90 {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(stream_join_barrier_align_duration_bucket[1m])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "p99 {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(stream_join_barrier_align_duration_bucket[1m])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "p999 {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(stream_join_barrier_align_duration_bucket[1m])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "pmax {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum by(le, actor_id, wait_side, job, instance)(rate(stream_join_barrier_align_duration_sum[1m])) / sum by(le,actor_id,wait_side,job,instance) (rate(stream_join_barrier_align_duration_count[1m]))",
       "legendFormat": "avg {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchange Send Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_send_size[15s])",
       "legendFormat": "{{up_actor_id}}->{{down_actor_id}}"
      }
     ]
    },
    {
     "title": "Exchange Recv Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_recv_size[15s])",
       "legendFormat": "{{up_actor_id}}->{{down_actor_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Hummock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_get_duration_count[1m])) by (job,instance)",
     "legendFormat": "get - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_iter_duration_count[1m])) by (job,instance)",
     "legendFormat": "iter - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_range_scan_duration_count[1m])) by (job,instance)",
     "legendFormat": "range_scan - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_range_reverse_scan_duration_count[1m])) by (job,instance)",
     "legendFormat": "reverse_range_scan - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_get_shared_buffer_hit_counts[1m])) by (job,instance)",
     "legendFormat": "shared_buffer hit - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(state_store_get_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(state_store_get_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_get_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_get_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_get_duration_count[1m]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(state_store_range_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(state_store_range_scan_duration_bucket[1m])) by (le,job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_range_scan_duration_sum[1m])) / sum by(le, job,instance) (rate(state_store_range_scan_duration_count[1m]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Reverse Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(state_store_range_reverse_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(state_store_range_reverse_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_reverse_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_range_reverse_scan_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_range_reverse_scan_duration_count[1m]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_iter_duration_sum[1m])) / sum by(le, job,instance) (rate(state_store_iter_duration_count[1m]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_iter_in_process_counts[1m])) by(job,instance)",
     "legendFormat": "iter_in_process_counts - {{instance}} "
    }
   ]
  },
  {
   "title": "Read Duration - Iter Pure Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_scan_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_scan_iter_duration_sum[1m])) / sum by(le, job,instance) (rate(state_store_iter_scan_duration_count[1m]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Block Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_sst_store_block_request_counts[1m])) by (job, instance, type)",
     "legendFormat": "{{type}} - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(state_store_meta_cache_size) by (job,instance)",
     "legendFormat": "meta cache - {{job}} @ {{instance}}"
    },
    {
     "expr": "avg(state_store_block_cache_size) by (job,instance)",
     "legendFormat": "data cache - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_duration_count[1m])) by (job,instance)",
     "legendFormat": "write batch - {{job}} @ {{instance}} "
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_l0_duration_count[1m])) by (job,instance)",
     "legendFormat": "l0 - {{job}} @ {{instance}} "
    }
   ]
  },
  {
   "title": "Write Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "shared_buffer p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "shared_buffer p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_batch_duration_bucket[1m])) by (le, job, instance))",
     "legendFormat": "shared_buffer p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_write_batch_duration_sum[1m]))  / sum by(le, job, instance)(rate(state_store_write_batch_duration_count[1m]))",
     "legendFormat": "shared_buffer avg - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, job, instance))",
     "legendFormat": "sync_remote p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, job, instance))",
     "legendFormat": "sync_remote p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_shared_buffer_sync_time_bucket[1m])) by (le, job, instance))",
     "legendFormat": "sync_remote p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_write_shared_buffer_sync_time_sum[1m]))  / sum by(le, job, instance)(rate(state_store_write_shared_buffer_sync_time_count[1m]))",
     "legendFormat": "sync_remote avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "sst read counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "sum(rate(state_store_bloom_filter_true_negative_counts[1m])) by (job,instance)",
     "legendFormat": "bloom filter true negative  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_bloom_filter_might_positive_counts[1m])) by (job,instance)",
     "legendFormat": "bloom filter might positive  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_iter_merge_sstable_counts_sum[1m]))  / sum by(le, job, instance)(rate(state_store_iter_merge_sstable_counts_count[1m]))",
     "legendFormat": "# merged ssts avg  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_get_key_size_bucket[1m])) by (le, job, instance)) + histogram_quantile(0.9, sum(rate(state_store_get_value_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_get_key_size_bucket[1m])) by (le, job, instance)) + histogram_quantile(0.99, sum(rate(state_store_get_value_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_get_key_size_bucket[1m])) by (le, job, instance)) + histogram_quantile(0.999, sum(rate(state_store_get_value_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_range_scan_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "scan p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_scan_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "scan p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_range_scan_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "scan p999 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_range_reverse_scan_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "reverse scan p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_reverse_scan_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "reverse scan p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_range_reverse_scan_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "reverse scan p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_size_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Count - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_item_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_item_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_item_bucket[1m])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "write kv pair counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_tuple_counts[1m])) by (job,instance)",
     "legendFormat": "write_batch_kv_pair_count - {{instance}} "
    }
   ]
  },
  {
   "title": "write throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_size_sum[1m]))by(job,instance) / sum(rate(state_store_write_batch_size_count[1m]))by(job,instance)",
     "legendFormat": "shared_buffer - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_sstable_size_sum[1m]))by(job,instance) / sum(rate(state_store_shared_buffer_to_sstable_size_count[1m]))by(job,instance)",
     "legendFormat": "sync - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "build sstable duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(state_store_shared_buffer_to_l0_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_shared_buffer_to_l0_duration_count[1m]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "merge iterators ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_iter_merge_seek_duration_count[1m])) by (job,instance)",
     "legendFormat": "MI seek  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_iter_merge_next_duration_count[1m])) by (job,instance)",
     "legendFormat": "MI next  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "row seq scan next duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(batch_row_seq_scan_next_duration_sum[1m])) / sum by(le, job, instance) (rate(batch_row_seq_scan_next_duration_count[1m]))",
     "legendFormat": "row_seq_scan next avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "merge iterators duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(state_store_iter_merge_seek_duration_sum[1m])) / sum by(le, job, instance) (rate(state_store_iter_merge_seek_duration_count[1m]))",
     "legendFormat": "mi_seek avg  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "gRPC Hummock Table Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 },
   "collapsed": true,
   "panels": [
    {
     "title": "get new TableID latency p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance)) ",
       "legendFormat": "hummock_client_ GetNewTableId_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "get new TableID latency p90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ GetNewTableId_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "get new TableID latency p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ GetNewTableId_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_GetNewTableId_p99 - {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ AddTables_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ AddTables_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "add tables latency p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ AddTables_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ AddTables_p99 - {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Hummock Compaction Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "report compation latency p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p50 - {{instance}}"
      }
     ]
    },
    {
     "title": "report compation latency p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p90 - {{instance}}"
      }
     ]
    },
    {
     "title": "report compation latency p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "hummock_manager_ ReportCompactionTasks_p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_ ReportCompactionTasks_p99 - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Hummock Version Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 },
   "collapsed": true,
   "panels": [
    {
     "title": "pin version latency p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_pinVersion_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_pinVersion_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "pin version latency p90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_pinVersion_p90 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_pinVersion_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "pin version latency p90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_pinVersion_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_pinVersion_p99 - {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p50",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_unpinVersion_p50 - {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p90 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_unpinVersion_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "unpin version latency p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le, job, instance))",
       "legendFormat": "hummock_manager_unpinVersion_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "hummock_client_unpinVersion_p99 - {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Catalog Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 },
   "collapsed": true,
   "panels": [
    {
     "title": "create latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[1m])) by (le))",
       "legendFormat": "Create_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/Create\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/Create\"}[1m]))",
       "legendFormat": "Create_avg"
      }
     ]
    },
    {
     "title": "drop latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[1m])) by (le))",
       "legendFormat": "Drop_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/Drop\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/Drop\"}[1m]))",
       "legendFormat": "Drop_avg"
      }
     ]
    },
    {
     "title": "get catalog latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[1m])) by (le))",
       "legendFormat": "GetCatalog_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/GetCatalog\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/GetCatalog\"}[1m]))",
       "legendFormat": "GetCatalog_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Cluster Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 },
   "collapsed": true,
   "panels": [
    {
     "title": "add worker node latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) by (le))",
       "legendFormat": "AddWorkerNode_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.ClusterService/AddWorkerNode\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.ClusterService/AddWorkerNode\"}[1m]))",
       "legendFormat": "AddWorkerNode_avg"
      }
     ]
    },
    {
     "title": "list all node latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) by (le))",
       "legendFormat": "ListAllNodes_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.ClusterService/ListAllNodes\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.ClusterService/ListAllNodes\"}[1m]))",
       "legendFormat": "ListAllNodes_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Stream Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 },
   "collapsed": true,
   "panels": [
    {
     "title": "create materialized view latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) by (le))",
       "legendFormat": "CreateMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[1m]))",
       "legendFormat": "CreateMaterializedView_avg"
      }
     ]
    },
    {
     "title": "drop materialized view latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) by (le))",
       "legendFormat": "DropMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/DropMaterializedView\"}[1m]))",
       "legendFormat": "DropMaterializedView_avg"
      }
     ]
    },
    {
     "title": "flush latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[1m])) by (le))",
       "legendFormat": "Flush_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/Flush\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/Flush\"}[1m]))",
       "legendFormat": "Flush_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Hummock Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 },
   "collapsed": true,
   "panels": [
    {
     "title": "version latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) by (le))",
       "legendFormat": "UnpinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/UnpinVersion\"}[1m]))",
       "legendFormat": "UnpinVersion_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) by (le))",
       "legendFormat": "PinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/PinVersion\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/PinVersion\"}[1m]))",
       "legendFormat": "PinVersion_avg"
      }
     ]
    },
    {
     "title": "snapshot latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) by (le))",
       "legendFormat": "UnpinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[1m]))",
       "legendFormat": "UnpinSnapshot_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) by (le))",
       "legendFormat": "PinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/PinSnapshot\"}[1m]))",
       "legendFormat": "PinSnapshot_avg"
      }
     ]
    },
    {
     "title": "compation latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) by (le))",
       "legendFormat": "ReportCompactionTasks_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[1m]))",
       "legendFormat": "ReportCompactionTasks_avg"
      }
     ]
    },
    {
     "title": "table latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) by (le))",
       "legendFormat": "AddTables_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/AddTables\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/AddTables\"}[1m]))",
       "legendFormat": "AddTables_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) by (le))",
       "legendFormat": "GetNewTableId_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/GetNewTableId\"}[1m]))",
       "legendFormat": "GetNewTableId_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC: Hummock Meta Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 },
   "collapsed": true,
   "panels": [
    {
     "title": "compaction_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum(irate(state_store_report_compaction_task_counts[1m])) by(job,instance)",
       "legendFormat": "report_compaction_task_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "version_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_version_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_version_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_version_latencyp90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_version_latency_sum[1m])) / sum(irate(state_store_pin_version_latency_count[1m]))",
       "legendFormat": "pin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_latency_sum[1m])) / sum(irate(state_store_unpin_version_latency_count[1m]))",
       "legendFormat": "unpin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_version_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "version_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_version_counts[1m])) by(job,instance)",
       "legendFormat": "pin_version_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_counts[1m])) by(job,instance)",
       "legendFormat": "unpin_version_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latencyp90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_snapshot_latency_sum[1m])) / sum(irate(state_store_pin_snapshot_latency_count[1m]))",
       "legendFormat": "pin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_snapshot_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_snapshot_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_latency_sum[1m])) / sum(irate(state_store_unpin_snapshot_latency_count[1m]))",
       "legendFormat": "unpin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_snapshot_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_snapshot_counts[1m])) by(job,instance)",
       "legendFormat": "pin_snapshot_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_counts[1m])) by(job,instance)",
       "legendFormat": "unpin_snapshot_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "table_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le,instance))",
       "legendFormat": "pin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "add_table_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_add_tables_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "add_table_latency_p90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_add_tables_latency_sum[1m])) / sum(irate(state_store_add_tables_latency_count[1m]))",
       "legendFormat": "add_table_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "get_new_table_id_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "get_new_table_id_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_table_id_latency_sum[1m])) / sum(irate(state_store_get_new_table_id_latency_count[1m]))",
       "legendFormat": "get_new_table_id_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_get_new_table_id_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "get_new_table_id_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "table_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(irate(state_store_add_tables_counts[1m]))by(job,instance)",
       "legendFormat": "add_tables_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_table_id_counts[1m]))by(job,instance)",
       "legendFormat": "get_new_table_id_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "compation_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p50 - {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p99 - {{instance}}"
      },
      {
       "expr": "sum(irate(state_store_report_compaction_task_latency_sum[1m])) / sum(irate(state_store_report_compaction_task_latency_count[1m]))",
       "legendFormat": "report_compaction_task_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_report_compaction_task_latency_bucket[1m])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p90 - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}