---
version: "3"
services:
  compactor-0:
    image: "ghcr.io/singularity-data/risingwave:latest"
    command:
      - compactor-node
      - "--host"
      - "0.0.0.0:6660"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1260"
      - "--metrics-level"
      - "1"
      - "--state-store"
      - "hummock+minio://hummockadmin:hummockadmin@minio-0:9301/hummock001"
      - "--meta-address"
      - "http://meta-node-0:5690"
    expose:
      - "6660"
      - "1260"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes: []
    environment: {}
    container_name: compactor-0
  compute-node-0:
    image: "ghcr.io/singularity-data/risingwave:latest"
    command:
      - compute-node
      - "--host"
      - "0.0.0.0:5688"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1222"
      - "--client-address"
      - "compute-node-0:5688"
      - "--metrics-level"
      - "1"
      - "--state-store"
      - "hummock+minio://hummockadmin:hummockadmin@minio-0:9301/hummock001"
      - "--meta-address"
      - "http://meta-node-0:5690"
    expose:
      - "5688"
      - "1222"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes: []
    environment: {}
    container_name: compute-node-0
  frontend-node-0:
    image: "ghcr.io/singularity-data/risingwave:latest"
    command:
      - frontend-node
      - "--host"
      - "0.0.0.0:4566"
      - "--meta-addr"
      - "http://meta-node-0:5690"
    expose:
      - "4566"
    ports:
      - "4566:4566"
    depends_on:
      - meta-node-0
    volumes: []
    environment: {}
    container_name: frontend-node-0
  meta-node-0:
    image: "ghcr.io/singularity-data/risingwave:latest"
    command:
      - meta-node
      - "--host"
      - "0.0.0.0:5690"
      - "--dashboard-host"
      - "0.0.0.0:5691"
      - "--prometheus-host"
      - "0.0.0.0:1250"
      - "--backend"
      - mem
    expose:
      - "5690"
      - "1250"
      - "5691"
    ports: []
    depends_on: []
    volumes: []
    environment: {}
    container_name: meta-node-0
  minio-0:
    image: "quay.io/minio/minio:latest"
    command:
      - server
      - "--address"
      - "0.0.0.0:9301"
      - "--console-address"
      - "0.0.0.0:9400"
      - /data
    expose:
      - "9301"
      - "9400"
    ports:
      - "9301:9301"
      - "9400:9400"
    depends_on: []
    volumes:
      - "minio-0:/data"
    entrypoint: "\n/bin/sh -c '\nset -e\nmkdir -p \"/data/hummock001\"\n/usr/bin/docker-entrypoint.sh \"$$0\" \"$$@\"\n'"
    environment:
      MINIO_PROMETHEUS_URL: "http://prometheus-0:9500"
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ROOT_PASSWORD: hummockadmin
      MINIO_ROOT_USER: hummockadmin
    container_name: minio-0
  prometheus-0:
    image: "prom/prometheus:latest"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.listen-address=0.0.0.0:9500"
    expose:
      - "9500"
    ports:
      - "9500:9500"
    depends_on: []
    volumes:
      - "prometheus-0:/prometheus"
    entrypoint: "\n/bin/sh -c '\nset -e\necho \"$$PROMETHEUS_CONFIG\" > /etc/prometheus/prometheus.yml\n/bin/prometheus \"$$0\" \"$$@\"\n'"
    environment:
      PROMETHEUS_CONFIG: "# --- THIS FILE IS AUTO GENERATED BY RISEDEV ---\nglobal:\n  scrape_interval: 1s\n  evaluation_interval: 5s\n\nscrape_configs:\n  - job_name: \"prometheus\"\n    static_configs:\n      - targets: [\"prometheus-0:9500\"]\n\n  - job_name: compute-job\n    static_configs:\n      - targets: [\"compute-node-0:1222\"]\n\n  - job_name: meta-job\n    static_configs:\n      - targets: [\"meta-node-0:1250\"]\n  \n  - job_name: minio-job\n    metrics_path: /minio/v2/metrics/cluster\n    static_configs:\n    - targets: [\"minio-0:9301\"]\n\n  - job_name: compactor-job\n    static_configs:\n      - targets: [\"compactor-0:1260\"]\n"
    container_name: prometheus-0
  redpanda:
    image: "docker.vectorized.io/vectorized/redpanda:latest"
    command:
      - redpanda
      - start
      - "--smp"
      - "1"
      - "--reserve-memory"
      - 0M
      - "--overprovisioned"
      - "--node-id"
      - "0"
      - "--kafka-addr"
      - "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092"
    expose:
      - "29092"
    ports:
      - "9092:9092"
    depends_on: []
    volumes: []
    environment: {}
    container_name: redpanda
volumes:
  minio-0:
    external: false
  prometheus-0:
    external: false
name: risingwave-compose
