[server]
heartbeat_interval_ms = 1000

[batch]

[streaming]
barrier_interval_ms = 250
checkpoint_frequency = 10

[storage]
shared_buffer_capacity_mb = 4096
sstable_size_mb = 256
block_size_kb = 1024
bloom_false_positive = 0.01
data_directory = "hummock_001"
block_cache_capacity_mb = 4096
meta_cache_capacity_mb = 1024
