[package]
name = "piestream_object_store"
version = "0.2.0-alpha"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
async_stack_trace = { path = "../utils/async_stack_trace" }
aws-config = { version = "0.49", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-endpoint = { version = "0.49", default-features = false }
aws-sdk-s3 = { version = "0.19", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-smithy-http = "0.49"
aws-smithy-types = "0.49"
aws-types = { version = "0.49", features = ["hardcoded-credentials"] }
bytes = { version = "1", features = ["serde"] }
crc32fast = "1.3.2"
fail = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = "0.14"
itertools = "0.10"
prometheus = { version = "0.13", features = ["process"] }
piestream_common = { path = "../common" }
spin = "0.9"
tempfile = "3"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
] }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.2.0-alpha", path = "../workspace-hack" }
