[package]
name = "piestream_bench"
version = "0.1.13"
edition = "2021"

[dependencies]
async-trait = "0.1"
aws-config = { version = "0.49", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-sdk-s3 = { version = "0.19", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-smithy-http = "0.49"
bcc = { version = "0.0.33", optional = true }
bytes = "1"
bytesize = { version = "1", features = ["serde"] }
clap = { version = "3", features = ["derive"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hdrhistogram = "7"
isahc = { version = "1", default-features = false }
itertools = "0.10"
libc = "0.2"
minitrace = "0.4"
minitrace-jaeger = "0.4"
moka = { version = "0.9", features = ["future"] }
nix = { version = "0.24.1", features = ["fs", "mman"] }
opentelemetry = { version = "0.17", optional = true, features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", optional = true, features = [
    "rt-tokio",
    "collector_client",
    "isahc",
    "isahc_collector_client",
] }
parking_lot = "0.12"
prometheus = { version = "0.13", features = ["process"] }
rand = "0.8"
piestream_common = { path = "../common" }
piestream_hummock_sdk = { path = "../storage/hummock_sdk" }
piestream_meta = { path = "../meta", features = ["test"] }
piestream_pb = { path = "../prost" }
piestream_rpc_client = { path = "../rpc_client" }
piestream_storage = { path = "../storage" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-stream = "0.1"
toml = "0.5"
tracing = "0.1"
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = "0.3.16"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.1.13", path = "../workspace-hack" }

[[bin]]
name = "file-cache-bench"
path = "file_cache_bench/main.rs"

[[bin]]
name = "s3-bench"
path = "s3_bench/main.rs"

[features]
bpf = ["bcc", "piestream_storage/bpf"]
trace = ["opentelemetry", "opentelemetry-jaeger", "tracing-opentelemetry", "tracing/release_max_level_trace"]
