[package]
name = "local_stats_alloc"
version = "0.2.0-alpha"
edition = "2021"
description = "Local allocator with statistics"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.2.0-alpha", path = "../../workspace-hack" }

[dev-dependencies]
