[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld", "--cfg", "tokio_unstable"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld", "--cfg", "tokio_unstable"
]

[build]
rustflags = ["--cfg", "tokio_unstable"]
