global:
  scrape_interval: 1s
  evaluation_interval: 5s
scrape_configs:
  - job_name: compute-job
    static_configs:
      - targets: ["${NODE1}:1222","${NODE2}:1222","${NODE3}:1222","${NODE4}:1222"]

  - job_name: meta-job
    static_configs:
      - targets: ["${META}:1250"]

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["${META}:9000"]

  - job_name: compactor-job
    static_configs:
      - targets: ["${NODE1}:1222","${NODE2}:1222","${NODE3}:1222","${NODE4}:1222"]

  - job_name: etcd
    static_configs:
      - targets: ["${NODE3}:2389","${NODE4}:2389"]