[package]
name = "pgwire"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
byteorder = "1.4"
bytes = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt", "macros"] }
tracing = { version = "0.1" }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
