[package]
name = "pgwire"
version = "0.2.0-alpha"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", default-features = false }
async-trait = "0.1"
byteorder = "1.4"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
itertools = "0.10"
openssl = "0.10.3"
pg_interval = "0.4"
postgres-types = { version = "0.2.4", features = ["derive","with-chrono-0_4"] }
regex = "1.5"
rust_decimal = { version = "1", features = ["db-tokio-postgres"] }
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = ["rt", "macros"] }
tokio-openssl = "0.6.3"
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.2.0-alpha", path = "../../workspace-hack" }

[dev-dependencies]
tokio-postgres = "0.7.7"
