[package]
name = "prost-helpers"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0"
proc-macro2 = { version = "1", default-features = false }
quote = "1"
syn = "1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.2.0-alpha", path = "../../workspace-hack" }
