[package]
name = "piestream_hummock_sdk"
version = "0.1.13"
edition = "2021"

[dependencies]
bytes = "1"
hex = "0.4"
itertools = "0.10"
num-derive = "0.3"
num-traits = "0.2"
parking_lot = "0.12"
parse-display = "0.6"
prost = "0.11"
piestream_common = { path = "../../common" }
piestream_pb = { path = "../../prost" }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.1.13", path = "../../workspace-hack" }
