[package]
edition = "2021"
name = "risedev"
version = "0.1.7"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytes = "1"
clap = { version = "3", features = ["derive"] }
console = "0.15"
dialoguer = "0.10"
enum-iterator = "0.8"
indicatif = "0.16"
isahc = "1"
itertools = "0.10"
kafka = { version = "0.8", default-features = false }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"
serde_yaml = "0.8"
tempfile = "3"
yaml-rust = "0.4"
