[package]
edition = "2021"
name = "risedev"
version = "0.1.10"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytes = "1"
clap = { version = "3", features = ["derive"] }
console = "0.15"
dialoguer = "0.10"
enum-iterator = "1"
indicatif = "0.16"
isahc = { version = "1", default-features = false, features = ["text-decoding"] }
itertools = "0.10"
kafka = { version = "0.9", default-features = false }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"
serde_yaml = "0.8"
tempfile = "3"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
yaml-rust = "0.4"
