[package]
edition = "2021"
name = "piestream_compute"
version = "0.2.0-alpha"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
async_stack_trace = { path = "../utils/async_stack_trace" }
byteorder = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "3", features = ["derive"] }
crc32fast = "1"
dyn-clone = "1"
either = "1"
farmhash = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
hyper = "0.14"
itertools = "0.10"
maplit = "1.0.2"
memcomparable = { path = "../utils/memcomparable" }
num-traits = "0.2"
parking_lot = "0.12"
paste = "1"
pprof = { version = "0.10", features = ["flamegraph"] }
prometheus = { version = "0.13" }
prost = "0.11"
piestream_batch = { path = "../batch" }
piestream_common = { path = "../common" }
piestream_common_service = { path = "../common/common_service" }
piestream_connector = { path = "../connector" }
piestream_hummock_sdk = { path = "../storage/hummock_sdk" }
piestream_pb = { path = "../prost" }
piestream_rpc_client = { path = "../rpc_client" }
piestream_source = { path = "../source" }
piestream_storage = { path = "../storage" }
piestream_stream = { path = "../stream" }
serde = { version = "1", features = ["derive"] }
serde-value = "0.7"
serde_json = "1"
smallvec = "1"
static_assertions = "1"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-stream = "0.1"
tonic = { version = "0.2", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tower-http = { version = "0.3", features = ["add-extension", "cors"] }
tracing = "0.1"
twox-hash = "1"
url = "2"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.2.0-alpha", path = "../workspace-hack" }

[dev-dependencies]
futures-async-stream = "0.2"
rand = "0.8"
tempfile = "3"

