[package]
edition = "2021"
name = "risingwave_compute"
version = "0.1.10"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
byteorder = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "3", features = ["derive"] }
crc32fast = "1"
dyn-clone = "1"
either = "1"
farmhash = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = "0.14"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
madsim = "=0.2.0-alpha.3"
maplit = "1.0.2"
memcomparable = { path = "../utils/memcomparable" }
num-traits = "0.2"
paste = "1"
prometheus = { version = "0.13" }
prost = "0.10"
rdkafka = { version = "0.28", features = ["cmake-build"] }
risingwave_batch = { path = "../batch" }
risingwave_common = { path = "../common" }
risingwave_connector = { path = "../connector" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_source = { path = "../source" }
risingwave_storage = { path = "../storage" }
risingwave_stream = { path = "../stream" }
serde = { version = "1", features = ["derive"] }
serde-value = "0.7"
serde_json = "1"
smallvec = "1"
static_assertions = "1"
thiserror = "1"
tokio = { version = "=0.2.0-alpha.3", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-stream = "0.1"
tonic = { version = "=0.2.0-alpha.3", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tower-http = { version = "0.3", features = ["add-extension", "cors"] }
tracing = { version = "0.1" }
twox-hash = "1"
url = "2"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
futures-async-stream = "0.2"
rand = "0.8"
tempfile = "3"

