[package]
name = "piestream_storage"
version = "0.1.10"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
auto_enums = { version = "0.7", features = ["futures"] }
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
crc32fast = "1"
crossbeam = "0.8.1"
dashmap = { version = "5", default-features = false }
dyn-clone = "1.0.4"
either = "1"
enum-as-inner = "0.5"
fail = "0.5"
farmhash = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
hyper = "0.14"
itertools = "0.10"
lazy_static = "1"
libc = "0.2"
log = "0.4"
lz4 = "1.23.1"
madsim = "=0.2.0-alpha.3"
memcomparable = { path = "../utils/memcomparable" }
minstant = "0.1"
moka = { version = "0.8", features = ["future"] }
nix = { version = "0.24.1", features = ["fs"] }
num-integer = "0.1"
num-traits = "0.2"
parking_lot = "0.12"
paste = "1"
prometheus = { version = "0.13", features = ["process"] }
prost = "0.10"
rand = "0.8"
piestream_common = { path = "../common" }
piestream_hummock_sdk = { path = "../storage/hummock_sdk" }
piestream_object_store = { path = "../object_store" }
piestream_pb = { path = "../prost" }
piestream_rpc_client = { path = "../rpc_client" }
# rocksdb = { git = "https://github.com/tikv/rust-rocksdb.git", rev = "fa83ff19", features = [
#     "encryption",
#     "static_libcpp",
# ], optional = true }
serde = { version = "1", features = ["derive"] }
smallvec = "1"
spin = "0.9"
tempfile = "3"
thiserror = "1"
# tikv-client = { git = "https://github.com/tikv/client-rust", rev = "5714b2", optional = true }
tokio = { version = "=0.2.0-alpha.3", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-metrics = "0.1.0"
tokio-retry = "0.3"
tokio-stream = "0.1"
tonic = { version = "=0.2.0-alpha.3", package = "madsim-tonic" }
tracing = { version = "0.1" }
twox-hash = "1"
value-encoding = { path = "../utils/value-encoding" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
zstd = "0.11.2"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "6599eb9dca74229b2c1fcc44118bef7eff127128" }
procfs = { version = "0.12", default-features = false }

[dev-dependencies]
criterion = "0.3"
piestream_meta = { path = "../meta", features = ["test"] }
piestream_test_runner = { path = "../test_runner" }
uuid = { version = "1", features = ["v4"] }

[features]
# rocksdb-local = ["rocksdb"]
# tikv = ["tikv-client"]
failpoints = ["fail/failpoints"]

[[bench]]
name = "bench_block_iter"
harness = false
# Enable debug if you want to generate flamegraph.
# debug = true

[[bench]]
name = "bench_lru_cache"
harness = false

[[bench]]
name = "bench_merge_iter"
harness = false

[[bench]]
name = "bench_fs_operation"
harness = false

[[bench]]
name = "bench_compression"
harness = false
