[package]
name = "piestream_rpc_client"
version = "0.1.13"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
async_stack_trace = { path = "../utils/async_stack_trace" }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
paste = "1"
rand = "0.8"
piestream_common = { path = "../common" }
piestream_hummock_sdk = { path = "../storage/hummock_sdk" }
piestream_pb = { path = "../prost" }
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tokio-stream = "0.1"
tonic = { version = "0.2", package = "madsim-tonic" }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
moka = { version = "0.9", features = ["future"] }
workspace-hack = { version = "0.1.13", path = "../workspace-hack" }
