version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "/usr/bin/kafka-topics", "--bootstrap-server", "broker:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  kafkacat:
    image: edenhill/kafkacat:1.6.0
    container_name: kafkacat
    depends_on:
      - broker
    entrypoint: /bin/sh
    volumes:
      - ./:/streaming
    tty: true

  mysql:
    image: debezium/example-mysql:latest
    hostname: mysql
    container_name: mysql
    ports:
     - 23306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw

  debezium:
    image: debezium/connect:latest
    hostname: debezium
    container_name: debezium
    ports:
     - 28083:8083
    links:
     - broker
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=broker:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  dbgen:
    image: tabbbb/tpch-dbgen:ubuntu  # tabbbb/tpch-dbgen:ubuntu
    hostname: dbgen
    container_name: dbgen
    entrypoint: /bin/sh
    volumes:
      - ./:/streaming
    tty: true
