name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    name: pr-title-checker
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"
