name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.WUTAO_PAT }}
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-close: -1
